#!/usr/bin/env bash
# ckb-node installer — Linux & macOS
# One command: curl -fsSL https://raw.githubusercontent.com/toastmanAu/ckb-access/main/ckb-node/install.sh | bash
set -euo pipefail

VERSION="0.204.0"
BINARY="ckb"
SERVICE_NAME="ckb-node"
REPO="nervosnetwork/ckb"

# ── Colours ──────────────────────────────────────────────
BOLD="\033[1m"; RESET="\033[0m"; GREEN="\033[32m"; YELLOW="\033[33m"; RED="\033[31m"; CYAN="\033[36m"
write_step()  { echo -e "\n${BOLD}${CYAN}▶ $*${RESET}"; }
write_ok()    { echo -e "  ${GREEN}✓${RESET} $*"; }
write_warn()  { echo -e "  ${YELLOW}⚠${RESET}  $*"; }
write_error() { echo -e "  ${RED}✗${RESET} $*"; }
write_info()  { echo -e "  ${CYAN}ℹ${RESET} $*"; }
ask() { local var="$1" prompt="$2" default="$3"; read -rp "  ${prompt} [${default}]: " val; eval "$var=\"${val:-$default}\""; }

# ── Platform detect ───────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
  Linux)
    case "$ARCH" in
      x86_64)  TARBALL="ckb_v${VERSION}_x86_64-unknown-linux-gnu.tar.gz" ;;
      aarch64) TARBALL="ckb_v${VERSION}_aarch64-unknown-linux-gnu.tar.gz" ;;
      *)       echo "Unsupported arch: $ARCH"; exit 1 ;;
    esac
    IS_LINUX=1; IS_MAC=0
    ;;
  Darwin)
    case "$ARCH" in
      x86_64) TARBALL="ckb_v${VERSION}_x86_64-apple-darwin.tar.gz" ;;
      arm64)  TARBALL="ckb_v${VERSION}_aarch64-apple-darwin.tar.gz" ;;
      *)      echo "Unsupported arch: $ARCH"; exit 1 ;;
    esac
    IS_LINUX=0; IS_MAC=1
    ;;
  *) echo "Unsupported OS: $OS"; exit 1 ;;
esac

TARBALL_URL="https://github.com/${REPO}/releases/download/v${VERSION}/${TARBALL}"

# ── Banner ────────────────────────────────────────────────
echo -e "${BOLD}"
echo "  ╔═══════════════════════════════════════╗"
echo "  ║   CKB Full Node Installer v1.0        ║"
echo "  ║   Nervos CKB · nervosnetwork           ║"
echo "  ╚═══════════════════════════════════════╝"
echo -e "${RESET}"
echo -e "  ${YELLOW}⚠  WARNING: Mainnet sync requires 200GB+ of disk space.${RESET}"
echo -e "  ${YELLOW}   Ensure your data directory has sufficient free space.${RESET}"
echo ""
echo "  Full node — validates all transactions, stores full chain history"
echo ""

# ── Config ────────────────────────────────────────────────
write_step "Configuration"
ask INSTALL_DIR  "Install directory" "$HOME/.ckb-node"
ask RPC_PORT     "RPC listen port"   "8114"
ask P2P_PORT     "P2P listen port"   "8115"

DATA_DIR="${INSTALL_DIR}"
LOG_FILE="${INSTALL_DIR}/ckb-node.log"

echo ""
write_ok "Install dir: $INSTALL_DIR"
write_ok "RPC port:    $RPC_PORT"
write_ok "P2P port:    $P2P_PORT"
echo ""

# ── Download binary ───────────────────────────────────────
write_step "Downloading ckb v${VERSION}"
mkdir -p "${INSTALL_DIR}/bin"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

if command -v curl &>/dev/null; then
  curl -fsSL -o "${TMP_DIR}/${TARBALL}" "$TARBALL_URL"
elif command -v wget &>/dev/null; then
  wget -q -O "${TMP_DIR}/${TARBALL}" "$TARBALL_URL"
else
  write_error "curl or wget required"; exit 1
fi

tar -xzf "${TMP_DIR}/${TARBALL}" -C "$TMP_DIR"
BIN_PATH="$(find "$TMP_DIR" -name "ckb" -type f | head -1)"
if [ -z "$BIN_PATH" ]; then
  write_error "ckb binary not found in tarball"; exit 1
fi
cp "$BIN_PATH" "${INSTALL_DIR}/bin/${BINARY}"
chmod +x "${INSTALL_DIR}/bin/${BINARY}"
write_ok "Binary installed: ${INSTALL_DIR}/bin/${BINARY}"

# ── Init node (generates config) ──────────────────────────
write_step "Initialising CKB node (mainnet)"
if [ -f "${INSTALL_DIR}/ckb.toml" ]; then
  write_warn "Config already exists — skipping init (delete ${INSTALL_DIR}/ckb.toml to reinitialise)"
else
  "${INSTALL_DIR}/bin/${BINARY}" init --chain mainnet -C "${INSTALL_DIR}"
  write_ok "Config generated by ckb init: ${INSTALL_DIR}/ckb.toml"
fi

# Patch RPC port if non-default
if [ "$RPC_PORT" != "8114" ]; then
  if command -v sed &>/dev/null; then
    sed -i.bak "s|listen_address = \"127.0.0.1:8114\"|listen_address = \"127.0.0.1:${RPC_PORT}\"|g" \
      "${INSTALL_DIR}/ckb.toml" 2>/dev/null || true
    write_ok "RPC port patched to $RPC_PORT"
  fi
fi

# Patch P2P port if non-default
if [ "$P2P_PORT" != "8115" ]; then
  if command -v sed &>/dev/null; then
    sed -i.bak "s|listen_addresses = \[\"/ip4/0.0.0.0/tcp/8115\"|listen_addresses = [\"/ip4/0.0.0.0/tcp/${P2P_PORT}\"|g" \
      "${INSTALL_DIR}/ckb.toml" 2>/dev/null || true
    write_ok "P2P port patched to $P2P_PORT"
  fi
fi

# ── Start script ──────────────────────────────────────────
write_step "Creating start script"
START_SCRIPT="${INSTALL_DIR}/start-ckb-node.sh"
cat > "$START_SCRIPT" << BASH
#!/usr/bin/env bash
RUST_LOG=info \\
  "${INSTALL_DIR}/bin/${BINARY}" run -C "${INSTALL_DIR}" \\
  >> "${LOG_FILE}" 2>&1
BASH
chmod +x "$START_SCRIPT"
write_ok "Start script: $START_SCRIPT"

# ── PATH ──────────────────────────────────────────────────
BIN_DIR="${INSTALL_DIR}/bin"
if ! echo "$PATH" | grep -q "$BIN_DIR"; then
  SHELL_RC="$HOME/.bashrc"
  [ "$IS_MAC" = "1" ] && SHELL_RC="$HOME/.zshrc"
  echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$SHELL_RC"
  write_ok "Added $BIN_DIR to PATH in $SHELL_RC"
fi

# ── Firewall ──────────────────────────────────────────────
write_step "Firewall"
if command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -q active; then
  ufw allow "${P2P_PORT}/tcp" &>/dev/null && write_ok "ufw: allowed port $P2P_PORT/tcp"
elif command -v firewall-cmd &>/dev/null; then
  firewall-cmd --add-port="${P2P_PORT}/tcp" --permanent &>/dev/null && firewall-cmd --reload &>/dev/null
  write_ok "firewalld: allowed port $P2P_PORT/tcp"
else
  write_warn "No firewall detected — ensure port $P2P_PORT/tcp is open if needed"
fi

# ── Service ───────────────────────────────────────────────
write_step "Installing service"
SYSTEMD_USER=0
if [ "$IS_LINUX" = "1" ] && command -v systemctl &>/dev/null; then
  SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
  if [ "$(id -u)" != "0" ]; then
    SERVICE_FILE="$HOME/.config/systemd/user/${SERVICE_NAME}.service"
    mkdir -p "$(dirname "$SERVICE_FILE")"
    SYSTEMD_USER=1
  fi
  cat > "$SERVICE_FILE" << UNIT
[Unit]
Description=CKB Full Node (mainnet)
After=network.target

[Service]
Environment=RUST_LOG=info
ExecStart=${INSTALL_DIR}/bin/${BINARY} run -C ${INSTALL_DIR}
WorkingDirectory=${INSTALL_DIR}
Restart=on-failure
RestartSec=10
StandardOutput=append:${LOG_FILE}
StandardError=append:${LOG_FILE}

[Install]
WantedBy=multi-user.target
UNIT
  if [ "$SYSTEMD_USER" = "1" ]; then
    systemctl --user daemon-reload
    write_ok "systemd user service installed: $SERVICE_NAME"
  else
    systemctl daemon-reload
    write_ok "systemd system service installed: $SERVICE_NAME"
  fi

elif [ "$IS_MAC" = "1" ]; then
  PLIST_LABEL="xyz.wyltek.ckb-node"
  PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"
  cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${PLIST_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${INSTALL_DIR}/bin/${BINARY}</string>
    <string>run</string>
    <string>-C</string>
    <string>${INSTALL_DIR}</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>RUST_LOG</key><string>info</string>
  </dict>
  <key>WorkingDirectory</key><string>${INSTALL_DIR}</string>
  <key>StandardOutPath</key><string>${LOG_FILE}</string>
  <key>StandardErrorPath</key><string>${LOG_FILE}</string>
  <key>KeepAlive</key><true/>
</dict>
</plist>
PLIST
  write_ok "launchd plist: $PLIST_PATH"
fi

# ── Smoke test ────────────────────────────────────────────
write_step "Smoke Test"
write_info "Starting node briefly to verify it launches..."

pkill -f "${BINARY}" 2>/dev/null || true
sleep 1

RUST_LOG=info \
  "${INSTALL_DIR}/bin/${BINARY}" run -C "${INSTALL_DIR}" \
  >> "${LOG_FILE}" 2>&1 &
SMOKE_PID=$!

SMOKE_PASS=0
RPC_URL="http://127.0.0.1:${RPC_PORT}"
printf "  Waiting for RPC on 127.0.0.1:${RPC_PORT}"
for i in $(seq 1 30); do
  sleep 1
  printf "."
  RESULT="$(curl -sf -X POST "$RPC_URL" \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"local_node_info","params":[],"id":1}' 2>/dev/null || true)"
  if echo "$RESULT" | grep -q '"node_id"'; then
    SMOKE_PASS=1
    break
  fi
done
echo ""

kill "$SMOKE_PID" 2>/dev/null || true
pkill -f "${BINARY}" 2>/dev/null || true
sleep 1

if [ "$SMOKE_PASS" = "1" ]; then
  write_ok "Smoke test passed ✓"
  NODE_ID="$(echo "$RESULT" | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d["result"]["node_id"])' 2>/dev/null || echo "unknown")"
  write_ok "Node ID: $NODE_ID"
else
  write_warn "Smoke test timed out — check logs: tail -f $LOG_FILE"
fi

# ── Summary ───────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}════════════════════════════════════════${RESET}"
echo -e "${BOLD}${GREEN}  CKB Full Node installed!${RESET}"
echo -e "${BOLD}${GREEN}════════════════════════════════════════${RESET}"
echo ""
echo -e "  ${BOLD}Version:${RESET}     v${VERSION}"
echo -e "  ${BOLD}Install dir:${RESET} $INSTALL_DIR"
echo -e "  ${BOLD}Config:${RESET}      ${INSTALL_DIR}/ckb.toml"
echo -e "  ${BOLD}Log:${RESET}         $LOG_FILE"
echo -e "  ${BOLD}P2P port:${RESET}    $P2P_PORT"
echo -e "  ${BOLD}RPC port:${RESET}    $RPC_PORT (localhost only)"
echo ""
echo -e "  ${BOLD}RPC endpoint:${RESET} http://127.0.0.1:${RPC_PORT}"
echo ""
echo -e "  ${YELLOW}⚠  Mainnet sync will take days and use 200GB+ of disk.${RESET}"
echo ""

# ── Offer to start ────────────────────────────────────────
write_step "Start Node?"
read -rp "  Start ckb-node now? [Y/n]: " START_NOW
START_NOW="${START_NOW:-Y}"
if [[ "$START_NOW" =~ ^[Yy] ]]; then
  if [ "$IS_LINUX" = "1" ] && command -v systemctl &>/dev/null; then
    if [ "$SYSTEMD_USER" = "1" ]; then
      systemctl --user enable "$SERVICE_NAME"
      systemctl --user start "$SERVICE_NAME"
      write_ok "Started: systemctl --user status $SERVICE_NAME"
    else
      systemctl enable "$SERVICE_NAME"
      systemctl start "$SERVICE_NAME"
      write_ok "Started: systemctl status $SERVICE_NAME"
    fi
  elif [ "$IS_MAC" = "1" ]; then
    launchctl load "$PLIST_PATH"
    write_ok "Started via launchd"
  else
    nohup "$START_SCRIPT" &
    write_ok "Started (nohup)"
  fi
  echo ""
  write_info "Check logs: tail -f $LOG_FILE"
  write_info "Check RPC:  curl -s -X POST http://127.0.0.1:${RPC_PORT} -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"local_node_info\",\"params\":[],\"id\":1}'"
else
  echo ""
  if [ "$IS_LINUX" = "1" ] && command -v systemctl &>/dev/null; then
    if [ "$SYSTEMD_USER" = "1" ]; then
      write_info "To start: systemctl --user enable --now $SERVICE_NAME"
    else
      write_info "To start: systemctl enable --now $SERVICE_NAME"
    fi
  elif [ "$IS_MAC" = "1" ]; then
    write_info "To start: launchctl load $PLIST_PATH"
  else
    write_info "To start: bash $START_SCRIPT"
  fi
fi

echo ""
write_ok "Done! CKB full node installed. Mainnet sync takes days — be patient."
echo ""
